### ISSUE TITLE
Update Tokio to 0.3

### ISSUE THREAD

**Issue by hatoo** [hatoo/oha#113]
Yay! https://tokio.rs/blog/2020-10-tokio-0-3

- [x] tokio-native-tls / tokio-rustls tokio-rs/tls#30
- [x] trust-dns bluejekyll/trust-dns#1250
- [x] hyper hyperium/hyper#2302

**Comment by svenstaro** [comment]
Looks like [trust-dns is now updated](https://github.com/bluejekyll/trust-dns/pull/1262).
